export const colliders = [
  {
    name: "profile",
    positions: { x: -185, y: 20, z: 94 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 1, y: 10, z: 1 },
    figure: "cylinder",
    group: "markers",
  },
  {
    name: "credits",
    positions: { x: -54, y: 20, z: 335 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 1, y: 10, z: 1 },
    figure: "cylinder",
    group: "markers",
  },
  {
    name: "hobbies",
    positions: { x: 284, y: 6, z: 176 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 1, y: 10, z: 1 },
    figure: "cylinder",
    group: "markers",
  },
  {
    name: "history",
    positions: { x: 148, y: 28, z: 37 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 1, y: 10, z: 1 },
    figure: "cylinder",
    group: "markers",
  },
  {
    name: "skills",
    positions: { x: 198, y: 13, z: -64 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 1, y: 10, z: 1 },
    figure: "cylinder",
    group: "markers",
  },
  {
    name: "contacts",
    positions: { x: -165, y: 26, z: -260 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 1, y: 10, z: 1 },
    figure: "cylinder",
    group: "markers",
  },
  {
    name: "portfolio",
    positions: { x: -45, y: 18, z: -83 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 1, y: 10, z: 1 },
    figure: "cylinder",
    group: "markers",
  },
  {
    name: "magic bridge",
    positions: { x: -59, y: 15, z: 20 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 1, y: 10, z: 1 },
    figure: "cylinder",
    group: "pointers",
  },
  {
    name: "wind mill",
    positions: { x: 40, y: 10, z: 249 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 1, y: 10, z: 1 },
    figure: "cylinder",
    group: "pointers",
  },
  {
    name: "book stand",
    positions: { x: 128, y: 16, z: 64 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 1, y: 10, z: 1 },
    figure: "cylinder",
    group: "pointers",
  },
  {
    name: "dead end",
    positions: { x: 168, y: 30, z: -251 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 1, y: 10, z: 1 },
    figure: "cylinder",
    group: "pointers",
  },
  {
    name: "tavern",
    positions: { x: -31, y: 16, z: -195 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 1, y: 10, z: 1 },
    figure: "cylinder",
    group: "pointers",
  },
  {
    name: "book stand",
    positions: { x: 156, y: 30, z: 45 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 4, y: 10, z: 1 },
    figure: "cylinder",
    group: "book stand",
  },
  {
    name: "house box",
    positions: { x: 298, y: 36, z: -20 },
    rotations: { x: 0, y: 43, z: 0 },
    dimensions: { x: 44, y: 30, z: 26 },
    figure: "cuboid",
    group: "blacksmith",
  },
  {
    name: "tent",
    positions: { x: 284, y: 22, z: -155 },
    rotations: { x: 0, y: 25, z: 0 },
    dimensions: { x: 10, y: 10, z: 17 },
    figure: "cuboid",
    group: "blacksmith",
  },
  {
    name: "tent",
    positions: { x: 250, y: 13, z: -175 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 10, y: 2, z: 3 },
    figure: "cuboid",
    group: "blacksmith",
  },
  {
    name: "anvils",
    positions: { x: 253, y: 10, z: -160 },
    rotations: { x: 0, y: 43, z: 0 },
    dimensions: { x: 3, y: 3, z: 1 },
    figure: "cylinder",
    group: "blacksmith",
  },
  {
    name: "anvils",
    positions: { x: 278, y: 10, z: -65 },
    rotations: { x: 0, y: 43, z: 0 },
    dimensions: { x: 4, y: 3, z: 1 },
    figure: "cylinder",
    group: "blacksmith",
  },
  {
    name: "bits",
    positions: { x: 298, y: 10, z: -65 },
    rotations: { x: 0, y: 43, z: 0 },
    dimensions: { x: 4, y: 2, z: 1 },
    figure: "cylinder",
    group: "blacksmith",
  },
  {
    name: "bits",
    positions: { x: 321, y: 12, z: -60 },
    rotations: { x: 0, y: 43, z: 0 },
    dimensions: { x: 4, y: 3, z: 1 },
    figure: "cylinder",
    group: "blacksmith",
  },
  {
    name: "bits",
    positions: { x: 320, y: 12, z: 0 },
    rotations: { x: 0, y: 43, z: 0 },
    dimensions: { x: 10, y: 3, z: 1 },
    figure: "cylinder",
    group: "blacksmith",
  },
  {
    name: "bits",
    positions: { x: 251, y: 10, z: -20 },
    rotations: { x: 0, y: 43, z: 0 },
    dimensions: { x: 4, y: 3, z: 1 },
    figure: "cylinder",
    group: "blacksmith",
  },

  {
    name: "house box",
    positions: { x: 346, y: 14, z: 248 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 20, y: 14, z: 26 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch front",
    positions: { x: 346, y: 3, z: 215 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 20, y: 1, z: 8 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch front",
    positions: { x: 325, y: 10, z: 207 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 17, y: 5, z: 0.5 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch front",
    positions: { x: 358, y: 10, z: 207 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 8, y: 5, z: 0.5 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch front",
    positions: { x: 365, y: 10, z: 214 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 0.5, y: 5, z: 7 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch sea side",
    positions: { x: 316, y: 3, z: 241 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 8, y: 1, z: 35 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch sea side",
    positions: { x: 290, y: -3, z: 244 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 3, y: 1, z: 7 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch sea side",
    positions: { x: 296, y: -1, z: 244 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 3, y: 1, z: 7 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch sea side",
    positions: { x: 301, y: 1, z: 244 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 3, y: 1, z: 7 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch sea side",
    positions: { x: 305, y: 2.5, z: 244 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 3, y: 1, z: 7 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch sea side",
    positions: { x: 309, y: 10, z: 222 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 0.5, y: 5, z: 15 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch sea side",
    positions: { x: 309, y: 10, z: 263 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 0.5, y: 5, z: 11 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch sea side",
    positions: { x: 317, y: 10, z: 274 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 8, y: 5, z: 0.5 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch sea side",
    positions: { x: 298, y: 6, z: 235 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 11, y: 5, z: 0.5 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch sea side",
    positions: { x: 298, y: 6, z: 251 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 11, y: 5, z: 0.5 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch sea side",
    positions: { x: 275, y: 0, z: 234 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 9, y: 5, z: 0.5 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch sea side",
    positions: { x: 235, y: 0, z: 234 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 9, y: 5, z: 0.5 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch sea side",
    positions: { x: 255, y: 0, z: 264 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 30, y: 5, z: 0.5 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch sea side",
    positions: { x: 285, y: 0, z: 257 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 0.5, y: 5, z: 5 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch sea side",
    positions: { x: 265, y: 0, z: 220 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 0.5, y: 5, z: 13 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "porch sea side",
    positions: { x: 244, y: 0, z: 220 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 0.5, y: 5, z: 13 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "pier",
    positions: { x: 258, y: -6, z: 248 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 35, y: 1, z: 17 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "pier",
    positions: { x: 255, y: -6, z: 217 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 12, y: 1, z: 14 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "boat",
    positions: { x: 255, y: -10, z: 192 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 21, y: 1, z: 7 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "water tower",
    positions: { x: 305, y: 35, z: 140 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 10, y: 20, z: 1 },
    figure: "cylinder",
    group: "seaHouse",
  },
  {
    name: "well",
    positions: { x: 400, y: 15, z: 219 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 5, y: 4, z: 1 },
    figure: "cylinder",
    group: "seaHouse",
  },
  {
    name: "palms",
    positions: { x: 346, y: 15, z: 174 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 4, y: 8, z: 1 },
    figure: "cylinder",
    group: "seaHouse",
  },
  {
    name: "palms",
    positions: { x: 339, y: 15, z: 315 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 4, y: 8, z: 1 },
    figure: "cylinder",
    group: "seaHouse",
  },
  {
    name: "barrels",
    positions: { x: 237.5, y: -1, z: 258 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 3, y: 3, z: 1 },
    figure: "cylinder",
    group: "seaHouse",
  },
  {
    name: "barrels",
    positions: { x: 271, y: -3, z: 258 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 3, y: 3, z: 1 },
    figure: "cylinder",
    group: "seaHouse",
  },
  {
    name: "barrels",
    positions: { x: 277, y: -2, z: 259.5 },
    rotations: { x: 0, y: 0, z: 0 },
    dimensions: { x: 3, y: 3, z: 1 },
    figure: "cylinder",
    group: "seaHouse",
  },
  {
    name: "rug",
    positions: { x: 315, y: 10, z: 309 },
    rotations: { x: 0, y: 170, z: 0 },
    dimensions: { x: 0.5, y: 5, z: 8 },
    figure: "cuboid",
    group: "seaHouse",
  },
  {
    name: "tavern",
    positions: { x: -231, y: 40, z: -355 },
    rotations: { x: 0, y: 80, z: 0 },
    dimensions: { x: 36, y: 30, z: 24 },
    figure: "cuboid",
    group: "tavern",
  },
  {
    name: "tavern",
    positions: { x: -264, y: 20, z: -350 },
    rotations: { x: 0, y: 80, z: 0 },
    dimensions: { x: 18, y: 8, z: 6 },
    figure: "cuboid",
    group: "tavern",
  },
  {
    name: "wind mill",
    positions: { x: -160, y: 32, z: 420 },
    rotations: { x: 0, y: 90, z: 0 },
    dimensions: { x: 20, y: 20, z: 1 },
    figure: "cylinder",
    group: "wind mill",
  },
  {
    name: "house",
    positions: { x: -258, y: 30, z: 5 },
    rotations: { x: 0, y: 90, z: 0 },
    dimensions: { x: 42, y: 15, z: 20 },
    figure: "cuboid",
    group: "main house",
  },
  {
    name: "porch",
    positions: { x: -258, y: 30, z: 55 },
    rotations: { x: 0, y: 90, z: 0 },
    dimensions: { x: 5, y: 15, z: 5 },
    figure: "cuboid",
    group: "main house",
  },
  {
    name: "stumps",
    positions: { x: -284, y: 22, z: 52 },
    rotations: { x: 0, y: 90, z: 0 },
    dimensions: { x: 5, y: 4, z: 6 },
    figure: "cuboid",
    group: "main house",
  },
  {
    name: "side house cylinder",
    positions: { x: -227, y: 30, z: 5 },
    rotations: { x: 0, y: 90, z: 0 },
    dimensions: { x: 12, y: 20, z: 1 },
    figure: "cylinder",
    group: "main house",
  },
  {
    name: "side house small cylinder",
    positions: { x: -196, y: 25, z: -22 },
    rotations: { x: 0, y: 90, z: 0 },
    dimensions: { x: 7, y: 10, z: 1 },
    figure: "cylinder",
    group: "main house",
  },
  {
    name: "side house small cylinder",
    positions: { x: -186, y: 22, z: 7 },
    rotations: { x: 0, y: 90, z: 0 },
    dimensions: { x: 5, y: 4, z: 1 },
    figure: "cylinder",
    group: "main house",
  },
  {
    name: "side house chair",
    positions: { x: -190, y: 20, z: 24 },
    rotations: { x: 0, y: 90, z: 0 },
    dimensions: { x: 2, y: 2, z: 2 },
    figure: "cuboid",
    group: "main house",
  },
  {
    name: "side house chair",
    positions: { x: -216, y: 20, z: 24 },
    rotations: { x: 0, y: 90, z: 0 },
    dimensions: { x: 2, y: 2, z: 2 },
    figure: "cuboid",
    group: "main house",
  },
  {
    name: "side house chair",
    positions: { x: -230, y: 25, z: 24 },
    rotations: { x: 0, y: 90, z: 0 },
    dimensions: { x: 10, y: 10, z: 10 },
    figure: "cuboid",
    group: "main house",
  },
  {
    name: "table set",
    positions: { x: -210, y: 21, z: 68 },
    rotations: { x: 0, y: 90, z: 0 },
    dimensions: { x: 3, y: 2, z: 7 },
    figure: "cuboid",
    group: "main house",
  },
  {
    name: "table set",
    positions: { x: -195, y: 19, z: 67 },
    rotations: { x: 0, y: 90, z: 0 },
    dimensions: { x: 2, y: 1, z: 5 },
    figure: "cuboid",
    group: "main house",
  },
  {
    name: "table set",
    positions: { x: -215, y: 20, z: 77 },
    rotations: { x: 0, y: 90, z: 0 },
    dimensions: { x: 2, y: 2, z: 2 },
    figure: "cuboid",
    group: "main house",
  },
  {
    name: "board",
    positions: { x: -75, y: 28, z: -66 },
    rotations: { x: 0, y: 85, z: 0 },
    dimensions: { x: 15, y: 15, z: 1 },
    figure: "cuboid",
    group: "board",
  },

  {
    name: "layer",
    positions: { x: 41, y: 0, z: 60 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 22, y: 1, z: 10 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "layer",
    positions: { x: -19, y: 0, z: 40 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 24, y: 1, z: 10 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "layer",
    positions: { x: -15, y: 2, z: 41 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 20, y: 1, z: 10 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "layer",
    positions: { x: 41, y: 2, z: 60 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 17, y: 1, z: 10 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "layer",
    positions: { x: 11, y: 4, z: 50 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 44, y: 1, z: 10 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "layer",
    positions: { x: 11, y: 6, z: 50 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 41, y: 1, z: 10 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "layer",
    positions: { x: 11, y: 8, z: 50 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 38, y: 1, z: 10 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "layer",
    positions: { x: 12, y: 10, z: 50 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 34, y: 1, z: 10 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "layer",
    positions: { x: 12, y: 12, z: 50 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 29, y: 1, z: 10 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "layer",
    positions: { x: 12, y: 14, z: 50 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 25, y: 1, z: 10 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "layer",
    positions: { x: 11, y: 16, z: 50 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 16, y: 1, z: 10 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "wall",
    positions: { x: 15, y: 24, z: 42 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 8, y: 5, z: 1 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "wall",
    positions: { x: 42, y: 16, z: 51 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 20, y: 10, z: 1 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "wall",
    positions: { x: -12, y: 16, z: 33 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 20, y: 10, z: 1 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "wall",
    positions: { x: 12, y: 24, z: 61 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 8, y: 5, z: 1 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "wall",
    positions: { x: 39, y: 16, z: 71 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 20, y: 10, z: 1 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "wall",
    positions: { x: -15, y: 16, z: 52 },
    rotations: { x: 0, y: 341, z: 0 },
    dimensions: { x: 20, y: 10, z: 1 },
    figure: "cuboid",
    group: "magic bridge",
  },
  {
    name: "bottom bridge",
    positions: { x: 187, y: 3, z: 170 },
    rotations: { x: 0, y: 59, z: 354 },
    dimensions: { x: 15, y: 1, z: 14 },
    figure: "cuboid",
    group: "bottom bridge",
  },
  {
    name: "bottom bridge",
    positions: { x: 187, y: 1, z: 170 },
    rotations: { x: 0, y: 59, z: 354 },
    dimensions: { x: 25, y: 1, z: 14 },
    figure: "cuboid",
    group: "bottom bridge",
  },
  {
    name: "bottom bridge",
    positions: { x: 187, y: -1, z: 170 },
    rotations: { x: 0, y: 59, z: 354 },
    dimensions: { x: 35, y: 1, z: 14 },
    figure: "cuboid",
    group: "bottom bridge",
  },
  {
    name: "bottom bridge",
    positions: { x: 187, y: -4, z: 170 },
    rotations: { x: 0, y: 59, z: 354 },
    dimensions: { x: 50, y: 1, z: 14 },
    figure: "cuboid",
    group: "bottom bridge",
  },
  {
    name: "layer",
    positions: { x: 77, y: 11, z: -248 },
    rotations: { x: 0, y: 10, z: 0 },
    dimensions: { x: 7, y: 1, z: 23 },
    figure: "cuboid",
    group: "top bridge",
  },
  {
    name: "layer",
    positions: { x: 77, y: 9, z: -248 },
    rotations: { x: 0, y: 10, z: 0 },
    dimensions: { x: 15, y: 1, z: 23 },
    figure: "cuboid",
    group: "top bridge",
  },
  {
    name: "layer",
    positions: { x: 77, y: 7, z: -248 },
    rotations: { x: 0, y: 10, z: 0 },
    dimensions: { x: 20, y: 1, z: 23 },
    figure: "cuboid",
    group: "top bridge",
  },
  {
    name: "layer",
    positions: { x: 77, y: 5, z: -248 },
    rotations: { x: 0, y: 10, z: 0 },
    dimensions: { x: 28, y: 1, z: 23 },
    figure: "cuboid",
    group: "top bridge",
  },
  {
    name: "layer",
    positions: { x: 76, y: 3, z: -248 },
    rotations: { x: 0, y: 10, z: 0 },
    dimensions: { x: 33, y: 1, z: 23 },
    figure: "cuboid",
    group: "top bridge",
  },
  {
    name: "layer",
    positions: { x: 78, y: 1, z: -248 },
    rotations: { x: 0, y: 10, z: 0 },
    dimensions: { x: 36, y: 1, z: 23 },
    figure: "cuboid",
    group: "top bridge",
  },
  {
    name: "layer",
    positions: { x: 80, y: -3, z: -248 },
    rotations: { x: 0, y: 10, z: 0 },
    dimensions: { x: 40, y: 1, z: 23 },
    figure: "cuboid",
    group: "top bridge",
  },

  {
    name: "wall",
    positions: { x: 75, y: 0, z: -270 },
    rotations: { x: 0, y: 10, z: 0 },
    dimensions: { x: 42, y: 20, z: 1 },
    figure: "cuboid",
    group: "top bridge",
  },
  {
    name: "wall",
    positions: { x: 83, y: 0, z: -227 },
    rotations: { x: 0, y: 10, z: 0 },
    dimensions: { x: 42, y: 20, z: 1 },
    figure: "cuboid",
    group: "top bridge",
  },
 
];
